version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: foxace-actualbudget_nginx_1
      APP_PORT: 5008
      PROXY_AUTH_ADD: "false"

  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - "5009:5009"
    volumes:
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_DATA_DIR}/ssl:/etc/nginx/ssl
    command: |
      sh -c "
        if [ ! -f /etc/nginx/ssl/cert.pem ]; then
          apk add --no-cache openssl &&
          openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -subj '/CN=192.168.1.60' -addext 'subjectAltName=IP:192.168.1.60';
        fi &&
        nginx -g 'daemon off;'
      "

  web:
    image: actualbudget/actual-server:latest
    user: 1000:1000
    restart: on-failure
    environment:
      - ACTUAL_PORT=5006
      - ACTUAL_TRUSTED_PROXIES=10.21.0.0/16
    volumes:
      - ${APP_DATA_DIR}/data:/data
