version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: foxace-actualbudget_web_1
      APP_PORT: 5006
      PROXY_AUTH_ADD: "false"

  caddy:
    image: caddy:2-alpine
    restart: on-failure
    ports:
      - "5007:5007"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${APP_DATA_DIR}/caddy_data:/data

  web:
    image: actualbudget/actual-server:latest
    user: 1000:1000
    restart: on-failure
    environment:
      - ACTUAL_PORT=5006
      - ACTUAL_TRUSTED_PROXIES=10.21.0.0/16
    volumes:
      - ${APP_DATA_DIR}/data:/data
