version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: foxace-actualbudget_web_1
      APP_PORT: 5006
      PROXY_AUTH_ADD: "false"
    volumes:
      - ./nginx-headers.conf:/etc/nginx/conf.d/headers.conf:ro

  web:
    image: actualbudget/actual-server:latest
    user: 1000:1000
    restart: on-failure
    environment:
      - ACTUAL_PORT=5006
      - ACTUAL_TRUSTED_PROXIES=10.21.0.0/16
    volumes:
      - ${APP_DATA_DIR}/data:/data
