version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-sonarr_server_1
      APP_PORT: 8989
  server:
    image: ghcr.io/hotio/sonarr:nightly
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home:/data
      - ${UMBREL_ROOT}/home:/mnt:rslave
    restart: on-failure
    networks:
      default:
        aliases:
          - sonarr

networks:
  default:
    name: umbrel_main_network
    external: true
