version: "3.7"
services:
  server:
    image: ghcr.io/hotio/sonarr:nightly
    container_name: foxace-sonarr_server_1
    restart: on-failure
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /home/umbrel/umbrel/home:/data
      - /home/umbrel/umbrel/home:/mnt:rslave
    networks:
      default:
        aliases:
          - sonarr

networks:
  default:
    name: umbrel_main_network
    external: true
