version: "3.7"
services:
  web:
    image: ghcr.io/sirrobot01/decypharr:latest
    container_name: foxace-decypharr_web_1
    restart: on-failure
    ports:
      - "8282:8282"
    volumes:
      - ${APP_DATA_DIR}/data/configs:/app
      - /home/umbrel/umbrel/home:/mnt:rshared
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
    networks:
      default:
        aliases:
          - decypharr

networks:
  default:
    name: umbrel_main_network
    external: true
