version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-decypharr_web_1
      APP_PORT: 8282
    networks:
      default:
  web:
    image: ghcr.io/sirrobot01/decypharr:latest
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/configs:/app
      - ${UMBREL_ROOT}/home:/mnt:rshared
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
    restart: on-failure
    networks:
      default:
        aliases:
          - decypharr

networks:
  default:
    name: umbrel_main_network
    external: true
