version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-playarr_server_1
      APP_PORT: 3001
    volumes:
      - ${APP_DATA_DIR}/umbrel-app.yml:/extra/umbrel-app.yml:ro
    networks:
      default:

  mongodb:
    image: mongo:6
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/mongodb:/data/db
    networks:
      default:
        aliases:
          - playarr-mongodb

  server:
    image: ghcr.io/elad-bar/playarr:latest
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - NODE_ENV=development
      - CACHE_DIR=/app/cache
      - LOGS_DIR=/app/logs
      - PORT=3001
      - DEFAULT_ADMIN_USERNAME=admin
      - DEFAULT_ADMIN_PASSWORD=umbrel
      - JWT_SECRET_KEY=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
      - MONGODB_URI=mongodb://foxace-playarr_mongodb_1:27017/playarr
    volumes:
      - ${APP_DATA_DIR}/data/cache:/app/cache
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - /home/umbrel/umbrel/home:/mnt:rslave
    networks:
      default:
        aliases:
          - playarr

networks:
  default:
    name: umbrel_main_network
    external: true
