version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-posterizarr_server_1
      APP_PORT: 8000
    networks:
      default:
  server:
    image: ghcr.io/fscorrupt/posterizarr:latest
    hostname: posterizarr
    user: "0:0"
    environment:
      - TZ=Europe/Paris
      - TERM=xterm
      - RUN_TIME=disabled
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${APP_DATA_DIR}/data/assets:/assets:rw
      - ${APP_DATA_DIR}/data/assetsbackup:/assetsbackup:rw
      - ${APP_DATA_DIR}/data/manualassets:/manualassets:rw
    restart: on-failure
    networks:
      default:
        aliases:
          - posterizarr

networks:
  default:
    name: umbrel_main_network
    external: true
