version: "3.7"

services:
  server:
    image: lscr.io/linuxserver/emby:4.9.3
    restart: on-failure
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - /home/umbrel/umbrel/home:/mnt:rslave
    devices:
      - /dev/dri:/dev/dri
    container_name: foxace-emby_server_1
