version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-placeholdarr_server_1
      APP_PORT: 8000
  server:
    image: ghcr.io/theindiearmy/placeholdarr:latest
    environment:
      - PLACEHOLDARR_HOST=0.0.0.0
      - PLACEHOLDARR_PORT=8000
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/data
      - ${UMBREL_ROOT}/data/storage:/data
    restart: on-failure
