version: "3.7"
services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-aura_server_1
      APP_PORT: 3000
    networks:
      default:
  server:
    image: ghcr.io/mediux-team/aura:v0.9.54
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - /home/umbrel/umbrel/home:/mnt
    restart: on-failure
    networks:
      default:
        aliases:
          - aura

networks:
  default:
    name: umbrel_main_network
    external: true
