version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-aura_server_1
      APP_PORT: 3000
    networks:
      default:
  server:
    image: ghcr.io/mediux-team/aura:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0022
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${UMBREL_ROOT}/home:/mnt:rslave
    restart: on-failure
    networks:
      default:
        aliases:
          - aura

networks:
  default:
    name: umbrel_main_network
    external: true
