version: "3.7"
services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-dispatcharr_server_1
      APP_PORT: 9191
    networks:
      default:
  server:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: on-failure
    networks:
      default:
        aliases:
          - dispatcharr

networks:
  default:
    name: umbrel_main_network
    external: true
