version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-plex_server_1
      APP_PORT: 32400
    networks:
      default:
  server:
    image: ghcr.io/hotio/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
      - PLEX_ADVERTISE_URL=http://192.168.1.60:32400
      - PLEX_NO_AUTH_NETWORKS=192.168.1.0/24
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/home:/mnt:rslave
    devices:
      - /dev/dri:/dev/dri
    restart: on-failure
    networks:
      default:
        aliases:
          - plex

networks:
  default:
    name: umbrel_main_network
    external: true
