version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-plex_server_1
      APP_PORT: 32400
  server:
    image: ghcr.io/hotio/plex:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/data/storage:/mnt:rshared
    devices:
      - /dev/dri:/dev/dri
    restart: on-failure
