version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: 192.168.1.60
      APP_PORT: 32400

  server:
    image: binhex/arch-plexpass:latest
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=Europe/Paris
      - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config
      - PLEX_ALLOWED_NETWORKS=192.168.1.0/24
      - ADVERTISE_IP=http://192.168.1.60:32400/
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/transcode:/transcode
      - ${UMBREL_ROOT}/home:/mnt:rslave
    devices:
      - /dev/dri:/dev/dri
