version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-radarr_server_1
      APP_PORT: 7878
      PROXY_AUTH_WHITELIST: "/api/*"
  server:
    image: ghcr.io/hotio/radarr:nightly
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /home/umbrel/umbrel/home:/data
      - /home/umbrel/umbrel/home:/mnt:rslave
    restart: on-failure
    networks:
      default:
        aliases:
          - radarr

networks:
  default:
    name: umbrel_main_network
    external: true
