version: "3.7"
services:
  server:
    image: ghcr.io/hotio/radarr:nightly
    container_name: foxace-radarr_server_1
    restart: on-failure
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /home/umbrel/umbrel/home:/data
      - /home/umbrel/umbrel/home:/mnt:rslave
    networks:
      default:
        aliases:
          - radarr

networks:
  default:
    name: umbrel_main_network
    external: true
