version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: foxace-octobot_web_1
      APP_PORT: 5001
      PROXY_AUTH_ADD: "false"

  web:
    image: drakkarsoftware/octobot:2.0.16
    restart: on-failure
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/user:/octobot/user
      - ${APP_DATA_DIR}/data/tentacles:/octobot/tentacles
      - ${APP_DATA_DIR}/data/logs:/octobot/logs
