version: "3.7"
services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-prowlarr_server_1
      APP_PORT: 9696
      PROXY_AUTH_WHITELIST: "/api/*"
    networks:
      default:
  server:
    image: ghcr.io/hotio/prowlarr:nightly
    container_name: foxace-prowlarr_server_1
    restart: on-failure
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    networks:
      default:
        aliases:
          - prowlarr

networks:
  default:
    name: umbrel_main_network
    external: true
