version: "3.7"
services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-agregarr_server_1
      APP_PORT: 7171
    networks:
      default:
  server:
    image: agregarr/agregarr:v2.3.0
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - /home/umbrel/umbrel/home:/mnt:rslave
    restart: on-failure
    networks:
      default:
        aliases:
          - agregarr

networks:
  default:
    name: umbrel_main_network
    external: true
