version: "3.7"

services:
  server:
    image: jellyfin/jellyfin:latest
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    network_mode: host
    user: "1000:1000"
    environment:
      - TZ=Europe/Paris
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_CACHE_DIR=/cache
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/cache:/cache
      - /home/umbrel/umbrel/home:/mnt:rslave
    devices:
      - /dev/dri:/dev/dri
