version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: foxace-suggestarr_server_1
      APP_PORT: 5000
  server:
    image: ciuse99/suggestarr:latest
    environment:
      - LOG_LEVEL=info
      - SUGGESTARR_PORT=5000
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config/config_files
    restart: on-failure
