version: "3.7"
services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-suggestarr_server_1
      APP_PORT: 5000
    networks:
      default:
  server:
    image: ciuse99/suggestarr:v2.1.6
    environment:
      - LOG_LEVEL=info
      - SUGGESTARR_PORT=5000
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config/config_files
    restart: on-failure
