version: "3.7"
services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: foxace-pulsarr_server_1
      APP_PORT: 3003
    networks:
      default:
  server:
    image: lakker/pulsarr:0.11.0
    environment:
      - TZ=Europe/Paris
      - PORT=3003
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: on-failure
    networks:
      default:
        aliases:
          - pulsarr

networks:
  default:
    name: umbrel_main_network
    external: true
